<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FilmsTempTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('films_temp')->delete();

        \DB::table('films_temp')->insert([
            0 => [
                'id' => 4,
                'nom_film' => 'Le Roi Lion',
                'categorie' => 'Film',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '2019',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-01 18:16:46',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            1 => [
                'id' => 5,
                'nom_film' => 'Le Roman de Renart',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '2005',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 3,
                'date_proposition' => '2025-10-01 18:58:46',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            2 => [
                'id' => 6,
                'nom_film' => 'Léo, roi de la jungle',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '1997',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 3,
                'date_proposition' => '2025-10-01 19:26:38',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            3 => [
                'id' => 7,
                'nom_film' => 'One Piece',
                'categorie' => 'Anime',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '1999',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 3,
                'date_proposition' => '2025-10-02 21:43:00',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            4 => [
                'id' => 8,
                'nom_film' => 'Volt, star malgrè lui',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '2008',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-03 10:15:45',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            5 => [
                'id' => 9,
                'nom_film' => 'La reine des neiges 1',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '2013',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-03 11:44:46',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            6 => [
                'id' => 11,
                'nom_film' => 'Olivier et compagnie',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '1988',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 09:56:37',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            7 => [
                'id' => 12,
                'nom_film' => 'Pinocchio',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '1940',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 10:20:53',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            8 => [
                'id' => 13,
                'nom_film' => 'Fantasia',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '1940',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 10:23:42',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            9 => [
                'id' => 14,
                'nom_film' => 'Dumbo',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '1941',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 10:25:39',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            10 => [
                'id' => 15,
                'nom_film' => 'Bambi 1',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '1942',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 10:28:10',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            11 => [
                'id' => 16,
                'nom_film' => 'Bambi 2',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '2006',
                'ordre_suite' => 2,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 10:30:16',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            12 => [
                'id' => 17,
                'nom_film' => 'Saludos Amigos',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '1942',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 10:35:04',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            13 => [
                'id' => 18,
                'nom_film' => 'Les Trois Caballeros',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '1944',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 10:37:14',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            14 => [
                'id' => 19,
                'nom_film' => 'Cendrillon',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '1950',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 10:43:09',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            15 => [
                'id' => 20,
                'nom_film' => 'Cendrillon 2 : Une vie de princesse',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '2002',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 10:46:29',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            16 => [
                'id' => 21,
                'nom_film' => 'Cendrillon 3 : Un retour dans le temps',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '2007',
                'ordre_suite' => 3,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 10:49:32',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            17 => [
                'id' => 22,
                'nom_film' => 'Alice au pays des merveilles',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '1951',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 10:52:51',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            18 => [
                'id' => 23,
                'nom_film' => 'Peter Pan',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '1953',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 10:55:18',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
            19 => [
                'id' => 24,
                'nom_film' => 'Peter Pan 2 : Retour au Pays imaginaire',
                'categorie' => 'Animation',
                'description' => null,
                'image_path' => null,
                'date_sortie' => '2002',
                'ordre_suite' => 2,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => null,
                'auteur_id' => null,
                'pays_id' => null,
                'propose_par' => 1,
                'date_proposition' => '2025-10-07 10:59:18',
                'statut' => 'approuve',
                'commentaire_admin' => '',
            ],
        ]);

    }
}
