<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FilmsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('films')->delete();

        \DB::table('films')->insert([
            0 => [
                'id' => 2,
                'nom_film' => 'Dragon 1',
                'categorie' => 'Animation',
                'description' => 'L\'histoire d\'Harold, jeune Viking peu à son aise dans sa tribu où combattre les dragons est le sport national. Sa vie va être bouleversée par sa rencontre avec un dragon qui va peu à peu amener Harold et les siens à voir le monde d\'un point de vue totalement différent.',
                'image_path' => '../publiclisteimg/2025-Dragon_1_1.jpg',
                'date_sortie' => '2010',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => 10,
                'studio_id' => 2,
                'auteur_id' => 2,
                'pays_id' => 1,
            ],
            1 => [
                'id' => 4,
                'nom_film' => 'Le Roi Lion',
                'categorie' => 'Film',
                'description' => 'Dans la savane africaine, le lionceau Simba se prépare à succéder à son père, le roi Mufasa. Mais son oncle Scar, avide de pouvoir, provoque la mort de Mufasa et pousse Simba à l’exil. Recueilli par Timon et Pumbaa, il grandit loin de son destin, jusqu’au jour où il doit affronter son passé pour reprendre sa place légitime de roi.',
                'image_path' => '../publiclisteimg/2019-Le_Roi_Lion_1.webp',
                'date_sortie' => '2019',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => 9,
                'studio_id' => 8,
                'auteur_id' => 4,
                'pays_id' => 1,
            ],
            2 => [
                'id' => 5,
                'nom_film' => 'Le Roman de Renart',
                'categorie' => 'Animation',
                'description' => 'Alors qu\'il cherche comment nuire à Renart le goupil, Ysengrin le loup découvre par hasard une carte indiquant le chemin d\'une caverne contenant un fabuleux trésor… Mais la carte tombe malencontreusement entre les mains de Renart. Ce dernier décide alors de se rendre à la caverne. Avec l\'aide de Rufus le rat maladroit, tous les deux vont vivre une grande aventure. ',
                'image_path' => '../publiclisteimg/2005-Le_Roman_de_Renart_1.jpg',
                'date_sortie' => '2005',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => 5,
                'studio_id' => 5,
                'auteur_id' => 5,
                'pays_id' => 5,
            ],
            3 => [
                'id' => 6,
                'nom_film' => 'Léo, roi de la jungle',
                'categorie' => 'Anime',
                'description' => 'Dans une jungle menacée par l’avidité humaine, Léo, lion blanc, tente de protéger son royaume et sa famille. Des humains, poussés par l’appât du gain, viennent chercher une pierre mystérieuse aux pouvoirs extraordinaires. Lorsque des épreuves, des maladies et des conflits éclatent, Léo doit faire face à des sacrifices pour sauver les siens.',
                'image_path' => '../publiclisteimg/1997-Leo_roi_de_la_jungle_1.jpg',
                'date_sortie' => '1997',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 6,
                'auteur_id' => 6,
                'pays_id' => 2,
            ],
            4 => [
                'id' => 7,
                'nom_film' => 'Volt, star malgrè lui',
                'categorie' => 'Animation',
                'description' => 'Volt, un chien vedette de série télé, croit posséder de vrais super-pouvoirs. Quand il se retrouve perdu loin des studios, il découvre le monde réel et apprend, avec l’aide d’une chatte et d’un hamster, que le vrai courage ne vient pas des pouvoirs mais du cœur.',
                'image_path' => '../publiclisteimg/2008-Volt_star_malgre_lui_1.webp',
                'date_sortie' => '2008',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 8,
                'pays_id' => 1,
            ],
            5 => [
                'id' => 8,
                'nom_film' => 'One Piece',
                'categorie' => 'Anime',
                'description' => 'Monkey D. Luffy, un jeune pirate au corps élastique, rêve de devenir Roi des Pirates en trouvant le légendaire trésor One Piece. Avec son équipage, les Mugiwara, il parcourt les mers, affronte ennemis et injustices, et poursuit son idéal de liberté et d’amitié.',
                'image_path' => '../publiclisteimg/1999-One_Piece_1.jpg',
                'date_sortie' => '1999',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => 1135,
                'note_moyenne' => null,
                'studio_id' => 7,
                'auteur_id' => 7,
                'pays_id' => 2,
            ],
            6 => [
                'id' => 9,
                'nom_film' => 'Raiponce',
                'categorie' => 'Animation',
                'description' => 'Raiponce, princesse aux cheveux magiques enfermée dans une tour par Mère Gothel, rêve de liberté. Sa rencontre avec Flynn Rider, un voleur en cavale, l’entraîne dans une aventure pleine d’humour, de romance et de découvertes sur sa véritable identité.',
                'image_path' => '../publiclisteimg/2010-Raiponce_1.webp',
                'date_sortie' => '2010',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 9,
                'pays_id' => 1,
            ],
            7 => [
                'id' => 10,
                'nom_film' => 'La reine des neiges 1',
                'categorie' => 'Animation',
                'description' => 'Quand Elsa révèle ses pouvoirs de glace et plonge le royaume d’Arendelle dans un hiver éternel, sa sœur Anna part à sa recherche. Accompagnée de Kristoff, Sven et Olaf, elle brave montagnes et dangers pour sauver Elsa et redonner l’été, découvrant la force de l’amour véritable.',
                'image_path' => '../publiclisteimg/2013-La_reine_des_neiges_1_1.jpg',
                'date_sortie' => '2013',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => 10,
                'studio_id' => 8,
                'auteur_id' => 10,
                'pays_id' => 1,
            ],
            8 => [
                'id' => 11,
                'nom_film' => 'Blanche Neige et les sept nains',
                'categorie' => 'Animation',
                'description' => 'Blanche-Neige, princesse au cœur pur, échappe à la jalousie de sa belle-mère, la Reine, qui veut être la plus belle du royaume. Recueillie par sept nains dans la forêt, elle trouve refuge et amitié. Mais la Reine, déguisée en vieille femme, lui fait croquer une pomme empoisonnée. Seul le baiser d’un prince la réveillera.',
                'image_path' => '../publiclisteimg/1937-Blanche_Neige_et_les_sept_nains_1.jpg',
                'date_sortie' => '1937',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 12,
                'pays_id' => 1,
            ],
            9 => [
                'id' => 12,
                'nom_film' => 'Olivier et compagnie',
                'categorie' => 'Animation',
                'description' => 'Un chat des rues débrouillard nommé Olivier rejoint une bande d’animaux dirigée par le rusé chien Dodger. Ensemble, ils survivent dans les rues de New York jusqu’à ce qu’Olivier soit adopté par une fillette riche, provoquant un affrontement entre deux mondes et une belle leçon d’amitié.',
                'image_path' => '../publiclisteimg/1988-Olivier_et_compagnie_1.jpg',
                'date_sortie' => '1988',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 11,
                'pays_id' => 1,
            ],
            10 => [
                'id' => 13,
                'nom_film' => 'Pinocchio',
                'categorie' => 'Animation',
                'description' => 'Dans un petit village, le menuisier Gepetto rêve qu’un jour sa marionnette, Pinocchio, devienne un vrai petit garçon. Exaucé par la Fée Bleue, Pinocchio prend vie, mais son innocence l’entraîne dans de nombreuses aventures. Entre mensonges, leçons et courage, il devra prouver qu’il a un cœur véritable.',
                'image_path' => '../publiclisteimg/1940-Pinocchio_1.jpg',
                'date_sortie' => '1940',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 13,
                'pays_id' => 1,
            ],
            11 => [
                'id' => 14,
                'nom_film' => 'Fantasia',
                'categorie' => 'Animation',
                'description' => 'Fantasia est un film d’animation expérimental où la musique classique prend vie à l’écran. À travers huit séquences, Disney marie images et symphonies : ballets de couleurs, créatures mythiques et nature animée. De L’Apprenti sorcier à La Nuit sur le mont chauve, chaque tableau célèbre l’imagination et le pouvoir de la musique.',
                'image_path' => '../publiclisteimg/1940-Fantasia_1.jpg',
                'date_sortie' => '1940',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 14,
                'pays_id' => 1,
            ],
            12 => [
                'id' => 15,
                'nom_film' => 'Dumbo',
                'categorie' => 'Animation',
                'description' => 'Dans un cirque ambulant, un éléphanteau aux grandes oreilles, surnommé Dumbo, devient la risée de tous. Séparé de sa mère, il trouve réconfort auprès de la petite souris Timothée. Moqué puis admiré, Dumbo découvre que ses oreilles, autrefois source de honte, lui permettent de voler et de devenir la vedette du cirque.',
                'image_path' => '../publiclisteimg/1941-Dumbo_1.webp',
                'date_sortie' => '1941',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 15,
                'pays_id' => 1,
            ],
            13 => [
                'id' => 16,
                'nom_film' => 'Bambi 1',
                'categorie' => 'Animation',
                'description' => 'Dans la quiétude de la forêt, naît Bambi, un jeune faon promis à devenir prince des bois. Guidé par ses amis Panpan et Fleur, il découvre la beauté et la cruauté de la nature. Entre joie, perte et maturité, Bambi apprend à grandir et à trouver sa place dans le cycle de la vie.',
                'image_path' => '../publiclisteimg/1942-Bambi_1_1.webp',
                'date_sortie' => '1942',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 16,
                'pays_id' => 1,
            ],
            14 => [
                'id' => 17,
                'nom_film' => 'Bambi 2',
                'categorie' => 'Animation',
                'description' => 'Après la mort de sa mère, le jeune Bambi est recueilli par son père, le Grand Prince de la forêt. Distant et sévère, celui-ci apprend peu à peu à connaître son fils. Ensemble, ils découvrent la force du lien qui les unit, tandis que Bambi cherche à prouver son courage et à trouver sa place parmi les siens.',
                'image_path' => '../publiclisteimg/2006-Bambi_2_2.webp',
                'date_sortie' => '2006',
                'ordre_suite' => 2,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 17,
                'pays_id' => 1,
            ],
            15 => [
                'id' => 18,
                'nom_film' => 'Saludos Amigos',
                'categorie' => 'Animation',
                'description' => 'Dans Saludos Amigos, quatre courts récits entraînent Donald, Dingo et leurs amis à travers l’Amérique du Sud. Entre humour, découverte et musique, le film célèbre la culture latino-américaine à travers le regard curieux des héros Disney, mêlant animation et prises de vue réelles dans un esprit de voyage et d’amitié.',
                'image_path' => '../publiclisteimg/1942-Saludos_Amigos_1.jpg',
                'date_sortie' => '1942',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 18,
                'pays_id' => 1,
            ],
            16 => [
                'id' => 19,
                'nom_film' => 'Les Trois Caballeros',
                'categorie' => 'Animation',
                'description' => 'Dans Les Trois Caballeros, Donald reçoit un coffret d’anniversaire qui l’emmène dans un voyage magique à travers l’Amérique latine. Accompagné du brésilien José Carioca et du mexicain Panchito, il découvre musiques, danses et paysages colorés. Entre rêve, humour et folklore, le film célèbre la joie et la diversité culturelle.',
                'image_path' => '../publiclisteimg/1944-Les_Trois_Caballeros_1.jpg',
                'date_sortie' => '1944',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 18,
                'pays_id' => 1,
            ],
            17 => [
                'id' => 20,
                'nom_film' => 'Cendrillon',
                'categorie' => 'Animation',
                'description' => 'Maltraitée par sa belle-mère et ses demi-sœurs, Cendrillon rêve d’une vie meilleure. Grâce à sa marraine la fée, elle se rend au bal du prince, transformée par la magie. Mais à minuit, le charme se brise, ne laissant qu’une pantoufle de verre. Ce souvenir mènera le prince à retrouver l’amour véritable.',
                'image_path' => '../publiclisteimg/1950-Cendrillon_1.jpg',
                'date_sortie' => '1950',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 19,
                'pays_id' => 1,
            ],
            18 => [
                'id' => 21,
                'nom_film' => 'Cendrillon 2 : Une vie de princesse',
                'categorie' => 'Animation',
                'description' => 'Fraîchement mariée au prince, Cendrillon découvre la vie au palais et les défis de son nouveau rôle. Entre étiquette, devoirs et sincérité, elle apprend qu’être princesse ne signifie pas renoncer à soi-même. Avec l’aide de ses amis, elle prouve que la vraie royauté vient du cœur.',
                'image_path' => '../publiclisteimg/2002-Cendrillon_2_Une_vie_de_princesse_1.webp',
                'date_sortie' => '2002',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 20,
                'pays_id' => 1,
            ],
            19 => [
                'id' => 22,
                'nom_film' => 'Cendrillon 3 : Un retour dans le temps',
                'categorie' => 'Animation',
                'description' => 'Lorsque la marâtre de Cendrillon s’empare de la baguette magique de la fée, elle remonte le temps pour empêcher le mariage de Cendrillon et du prince. Plongée dans un monde bouleversé, Cendrillon doit se battre pour rétablir la vérité et prouver que le véritable amour triomphe de toute magie.',
                'image_path' => '../publiclisteimg/2007-Cendrillon_3_Un_retour_dans_le_temps_3.jpg',
                'date_sortie' => '2007',
                'ordre_suite' => 3,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 21,
                'pays_id' => 1,
            ],
            20 => [
                'id' => 23,
                'nom_film' => 'Alice au pays des merveilles',
                'categorie' => 'Animation',
                'description' => 'Curieuse et rêveuse, Alice suit un lapin blanc jusque dans un monde étrange où règnent absurdité et fantaisie. Entre le Chat du Cheshire, le Chapelier fou et la Reine de Cœur, elle traverse un univers plein de mystères. Ce voyage initiatique l’amène à questionner la logique et à découvrir la force de son imagination.',
                'image_path' => '../publiclisteimg/1951-Alice_au_pays_des_merveilles_1.webp',
                'date_sortie' => '1951',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 19,
                'pays_id' => 1,
            ],
            21 => [
                'id' => 24,
                'nom_film' => 'Peter Pan',
                'categorie' => 'Animation',
                'description' => 'Une nuit, Peter Pan emmène Wendy et ses frères voler jusqu’au Pays Imaginaire, où les enfants ne grandissent jamais. Entre fées, pirates et sirènes, ils vivent d’incroyables aventures face au redoutable Capitaine Crochet. Mais Wendy comprend que grandir fait aussi partie de la plus belle des aventures.',
                'image_path' => '../publiclisteimg/1953-Peter_Pan_1.jpg',
                'date_sortie' => '1953',
                'ordre_suite' => 1,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 19,
                'pays_id' => 1,
            ],
            22 => [
                'id' => 25,
                'nom_film' => 'Peter Pan 2 : Retour au Pays imaginaire',
                'categorie' => 'Animation',
                'description' => 'Pendant la Seconde Guerre mondiale, Jane, la fille de Wendy, ne croit plus aux contes. Enlevée par le capitaine Crochet et emmenée au Pays Imaginaire, elle rencontre Peter Pan et les Enfants Perdus. Pour rentrer chez elle, elle devra retrouver sa foi en la magie, l’amitié et le pouvoir de rêver.',
                'image_path' => '../publiclisteimg/2002-Peter_Pan_2_Retour_au_Pays_imaginaire_2.jpg',
                'date_sortie' => '2002',
                'ordre_suite' => 2,
                'saison' => null,
                'nbrEpisode' => null,
                'note_moyenne' => null,
                'studio_id' => 8,
                'auteur_id' => 22,
                'pays_id' => 1,
            ],
        ]);

    }
}
